- .drone.star
- package.json
Steps that should happen:
- Tests
- Lint
- Build
- Release (on tag)
- Build
- Github release
- NPM release
> Add tests and release jobs into drone

- .drone.star
By default, the access is set to private. This should push the package as a public one.
> Set npm access to public

- package.json
Our npm username is ownclouders so it needs to be reflected in the package name.
> Use correct org name

- .drone.star
- changelog/CHANGELOG.tmpl
The template was copied over from our boilerplate without removing all escaping.
> Fix changelog template

- changelog/unreleased/do-not-import-vue
- src/App.vue
We've stopped importing Vue because it is not bundled during the build process and needs to be included as a global variable in the target web application.
> Do not import Vue

- changelog/unreleased/reset-selection
- src/components/ListResources.vue
We've added reset of selected resources when a folder is opened. This prevents from having selected resources which are not visible.
> Add selected resources reset

- changelog/unreleased/bootstrap-vue
- src/App.vue
- src/main.js
- src/vue.js
Enable access to the Vue instance via window object and rename app component to prevent an endless created loop.
> Bootstrap Vue

- src/services/auth.js
Currently you cannot change the redirect_uri when using OAuth2 or the old style of openidconnect configuration. As the file picker is to be used as parts of other projects and requires its own oidc-callback.html file to be redirected to I propose to make the redirect_uri configurable. The advantage is that the oidc-callback.html then can reside in any subfolder of the project.
> Manual setting of redirect_uri in auth service

- changelog/unreleased/enhancement-config-json
- docs/installation.md
- tests/unit/__snapshots__/filePicker.spec.js.snap
This PR adapts the docs regarding config to the most recent changes.
> Adapt docs for config

- changelog/unreleased/enhancement-cancellation
- changelog/unreleased/enhancement-select-button
- docs/installation.md
- src/App.vue
- src/components/FilePicker.vue
- src/components/ListHeader.vue
- tests/helpers/mocks.js
- tests/unit/__snapshots__/filePicker.spec.js.snap
- tests/unit/filePicker.spec.js
This PR adds properties for providing labels for the `select` and `cancel` buttons. The `cancel` button is entirely new with this PR.
Todo:
> Cancel and select button

- changelog/unreleased/enhancement-lib-target
- docs/installation.md
- package.json
- src/App.vue
- yarn.lock
If we want to include file picker in a Vue based project, we should use library target instead of the web component. This PR creates new build scripts `build:wc` and `build:lib` which can be run together via `build`.
> Build as a vue lib

- changelog/unreleased/enhancement-initial-focus
- src/App.vue
We've added an initial focus so that when the File picker is mounted, it immediately becomes focused.
> feat: add initial focus

- .drone.star
- .eslintrc.js
- changelog/unreleased/bugfix-emit-current-folder
- jest.config.js
- package.json
- src/components/FilePicker.vue
- src/components/ListHeader.vue
- src/components/ListResources.vue
- tests/integration/config/jest.init.js
- tests/integration/specs/filePicker.spec.js
- yarn.lock
When selecting the current folder in the location picker, an empty array has been emitted. We've fixed this by emitting the current folder.
Short note: this is our first feature with integration tests 🥳 
- fixes #39
> fix: emit current folder

- changelog/unreleased/bugfix-do-not-propagate-click-event
- src/components/ListResources.vue
- tests/integration/specs/filePicker.spec.js
When clicking on the checkbox to select a resource, it hasn't been selected because a click on the row would have been caught as well which would reset the selection again. We've fixed this issue by not propagating the click event on checkbox to the parent.
> fix: do not propagate click event on checkbox

- l10n/translations.json
This PR fixes one german string translation. Omitted the changelog because translations should not come from PRs but from transifex in the long run.
> Fix german translation for last modified date

- changelog/unreleased/bugfix-emit-location-as-array
- changelog/unreleased/enhancement-folderLoaded-event
- docs/accessing-resources.md
- docs/component-reference.md
- src/App.vue
- src/components/FilePicker.vue
- tests/integration/specs/filePicker.spec.js
- tests/unit/filePicker.spec.js
When loading new folder in Location picker, we are emitting an "update" with the current route as an argument. We've fixed that the argument has type array now so that it is consistent with all other arguments returned in the `update` event. We've also added event called `folderLoaded` that is emitted every time a loading of any folder has ended.
It is emitting the current folder as an argument.
Fixes #71
> feat: emit current folder and fix update type

- changelog/unreleased/bugfix-current-breadcrumb-item
- src/components/ListHeader.vue
- tests/unit/listHeader.spec.js
We've fixed the last item in the breadcrumb which is equal to the current folder so that it is not interactable anymore.
- fixes #64
> fix: non-interactible current folder in breadcrumbs

- changelog/unreleased/change-use-memory-storage
- changelog/unreleased/enhancement-use-memory-storage
- docs/installation.md
- public/oidc-callback.html
- src/services/auth.js
By specifying `storage: memory` in the json config of file picker, we can use the in-memory storage instead of session storage.
> feat: use in-memory storage

- changelog/unreleased/enhancement-focus-mngmt
- docs/component-reference.md
- docs/focus-management.md
- src/App.vue
- src/components/FilePicker.vue
- src/components/ListHeader.vue
- src/mixins/accessibility.js
- tests/integration/config/jest.init.js
- tests/integration/specs/filePicker.spec.js
- tests/unit/filePicker.spec.js
We've added focus management so that the last breadcrumb item will be focus after a folder has been loaded.
By default, this focus management is disabled on the first load when opening the file picker.
To enable it also during the first load, set prop `isInitialFocusEnabled` to `true`.
> feat: handle focus after folder load

- changelog/unreleased/enhancement-token-event
- docs/component-reference.md
- src/App.vue
- src/components/FilePicker.vue
Since the `file-picker` handles authentication the embedding party should be able to use the access token for further ownCloud API calls (e.g. TUS upload after target folder selection).
A more advanced option would be to externalize the authentication and hand over an access token to the file-picker and also use it for the other API calls. For the sake of dev simplicity the new event described above is a valid approach as well.
> Emit access token

- docs/accessing-resources.md
- docs/getting-started.md
Right from the start make it known that the File picker returns only the resource representation instead of the actual file and add an example of how to upload a file with TUS into the selected location.
> docs: create example of upload into selected location

- changelog/unreleased/bugfix-clear-state-when-unauthorized
- changelog/unreleased/bugfix-token-renewal-hook
- src/App.vue
- src/components/FilePicker.vue
- src/services/auth.ts
Fixes two things:
1. adds 401 error handling -> user will be presented with the authenticate button again. Trying to authenticate and then replay the previously failed requests is unfortunately a bigger task - won't happen in this PR (and also not planned effort short term). Did this by adding a) a response interceptor on the axios instance (used for graph API) and b) auth error handling in the catch block of the `loadFolder` method (webdav).
2. the filepicker initialization had a bug which made sense to solve here: if the user was initially authenticated the userLoaded event would always call `updateBearerToken`. If the user was initially unauthenticated the userLoaded event would always call `initApp` (which does a lot of things that are not needed on subsequent token renewals). …
> Fix auth renewal

- src/App.vue
When the `bearerToken` prop is set, the token needs to be used instead of trying to get it from the auth instance which of course fails.
> fix: use token prop when set

- src/components/ListHeader.vue
Use label "Choose" instead of "Select resources".
- refs https://github.com/owncloud/file-picker/issues/194
> feat: rename select action label in resource picker

- examples/oc10/index.html
- examples/ocis/index.html
- patches/@vue__web-component-wrapper@1.3.0.patch
- pnpm-lock.yaml
- src/App.vue
- src/components/ListHeader.vue
- src/components/ListResources.vue
- src/components/SpacesList.vue
- src/composables/useA11y.ts
- src/main.lib.ts
- src/main.wc.ts
- src/style.css
- tests/integration/specs/filePicker.spec.js
- vite.config.ts
Since some of the styles used in the File picker can have an effect on the parent document, it is needed to handle the styles inside of shadowRoot and have them isolated.
One challenge though - vite does not inject styles into the built bundle when library mode is used in the config (open issue here https://github.com/vitejs/vite/issues/1579). This of course brings the problem of including the style inside the shadowRoot. Some plugins exists that can still handle the injection but unfortunately does not work with custom elements as it anyway tries to add the styles into the document instead of shadowRoot. This forces us to append the styles ourselves into the shadowRoot when the custom element is being constructed.
This change does not affect the lib build as the style.css file is still …
> feat: bring back shadowRoot

- package.json
- pnpm-lock.yaml
Update the [vue-tsc](https://www.npmjs.com/package/vue-tsc) dependency to version 1.8.3. This update gets fixes the error outputted during linting about importing the ts config. Thanks for the hint @dschmidt
> chore: update vue-tsc to 1.8.3

- .github/settings.yml
Ref: https://github.com/owncloud/enterprise/issues/5832
Required status checks were moved to rulesets.
> fix settings to work with ci bot
